### ISSUE TITLE
When more languages will be available ?

### ISSUE THREAD

**Issue by Impre-visible** [Goel25/ClonePilotExtension#2]
i love the extension, but i use many languages, like python, html/css, and others, at least add python to the extension its incredible

**Comment by leognon** [comment]
Unfortunately, I'm no longer working on this project, but if you watch the YouTube video, you may be able to figure out how to add your own languages. Then you can set up your own database and parse whatever language you need from StackOverflow.

Let me know if you need any more help.

**Comment by Impre-visible** [comment]
I decided to recode everything, to allow to use multiple words

**Comment by leognon** [comment]
Great, good luck!
